[features]
seeds = false
skip-lint = false

[programs.localnet]
mandala_settler = "MANDALA11111111111111111111111111111111111111"  # Replace after first build/deploy

[programs.devnet]
mandala_settler = "MANDALA11111111111111111111111111111111111111"

[programs.mainnet]
mandala_settler = "MANDALA11111111111111111111111111111111111111"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"          # Change to "mainnet" or "localnet" as needed
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"

[workspace]
members = ["programs/mandala_settler"]
